#!/bin/bash

set -e

updateRepo() {
    URL=$1
    DIR=$2
    BRANCH=${3:-$(git rev-parse --abbrev-ref HEAD)}
    git clone ${URL} ${DIR} || echo Repository ${DIR} already exists.
    cd ${DIR}

    if [[ ${BRANCH} == master || ${BRANCH} == R* ]]
    then
        git checkout -B "${BRANCH}" "origin/${BRANCH}"
    else
        git checkout -B master origin/master
    fi

    git pull

    cd ..
} 

cd $(cd $(dirname "$0"); pwd)

updateRepo https://github.com/Juniper/contrail-controller.git controller
updateRepo https://github.com/Juniper/contrail-generateDS.git generateds
updateRepo https://github.com/Juniper/contrail-java-api.git contrail-java-api

cd contrail-java-api
mvn clean 
mvn install
cd ..

if [ -z "$1" ]
then 
    echo "vRO host was not specified."
else
    REPO_HOST="-Drepo.host=$1"
fi

cd plugin
mvn clean 
mvn install ${REPO_HOST}
