#!/bin/sh

updateRepo() {
    URL=$1
    DIR=$2
    BRANCH=${3:-$(git rev-parse --abbrev-ref HEAD)}
    git clone $URL $DIR || echo Repository $DIR already exists.
    cd $DIR 
    git pull
    git checkout $BRANCH
    cd ..
} 

cd $(cd $(dirname "$0"); pwd)

updateRepo https://github.com/Juniper/contrail-controller.git controller R4.0
updateRepo https://github.com/Juniper/contrail-generateDS.git generateds
updateRepo https://github.com/Juniper/contrail-java-api.git contrail-java-api

cd contrail-java-api
mvn clean 
mvn install
cd ..

if [ -z "$1" ]
then 
    echo "vRO host was not specified."
else
    REPO_HOST="-Drepo.host=$1"
fi

cd plugin
mvn clean 
mvn install $REPO_HOST
