/*
 * Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
 */

package net.juniper.contrail.vro.config.constants

const val createContrailControllerConnectionWorkflowName = "Create Contrail controller connection"
const val deleteContrailControllerConnectionWorkflowName = "Delete Contrail controller connection"
const val editFirewallRuleWorkflowName = "Edit firewall rule"
const val addRuleToNetworkPolicyWorkflowName = "Add rule to network policy"
const val editRuleOfNetworkPolicyWorkflowName = "Edit rule of network policy"
const val removeRuleFromNetworkPolicyWorkflowName = "Remove rule from network policy"
const val addRuleToSecurityGroupWorkflowName = "Add rule to security group"
const val editRuleOfSecurityGroupWorkflowName = "Edit rule of security group"
const val removeRuleFromSecurityGroupWorkflowName = "Remove rule from security group"
const val addServiceToServiceGroupWorkflowName = "Add service to service group"
const val editServiceOfServiceGroupWorkflowName = "Edit service of service group"
const val removeServiceFromServiceGroupWorkflowName = "Remove service from service group"
const val deleteTagTypeWorkflowName = "Delete tag type"
const val createTagTypeWorkflowName = "Create tag type"
const val removeSubnetFromVirtualNetworkWorkflowName = "Remove subnet from virtual network"
const val addSubnetToVirtualNetworkWorkflowName = "Add subnet to virtual network"
const val addSubnetToNetworkIpamWorkflowName = "Add subnet to network IPAM"
const val removeSubnetFromNetworkIpamWorkflowName = "Remove subnet from network IPAM"
const val addSubnetToAddressGroupWorkflowName = "Add subnet to address group"
const val removeSubnetFromAddressGroupWorkflowName = "Remove subnet from address group"
const val addLabelToAddressGroupWorkflowName = "Add label to Address Group"
const val removeLabelFromAddressGroupWorkflowName = "Remove label from Address Group"
const val createApplicationPolicySetWithFirewallPoliciesInProjectWorkflowName = "Create application policy set with firewall policies in project"
const val createGlobalApplicationPolicySetWithFirewallPoliciesWorkflowName = "Create global application policy set with firewall policies"
const val commitDraftsInProjectWorkflowName = "Commit drafts in project"
const val commitGlobalDraftsWorkflowName = "Commit global drafts"
const val discardDraftsInProjectWorkflowName = "Discard drafts in project"
const val discardGlobalDraftsWorkflowName = "Discard global drafts"
const val editGlobalConfiguration = "Edit global configuration"